#+TITLE: 2014年春节回家记

* 本年度在百度的最后一天

今天就写成一个列表吧：
1. 昨晚玩手机3点睡觉
2. 凌晨栗涛和晓明动身回家，我被弄醒N次
3. 凌晨六点大舅打电话过来，接完电话后，我睡不着了
4. 在床上躺到7点半后，我起床了，然后骑车去地铁旁边买了油饼和豆浆回来吃
5. 回来继续上网，直到10点半，我洗了个澡，洗完后时间是11点20
6. 12点出门，去龙腾六对面的快捷酒店下的代售点取票，然后去超市排队买稻香村
7. 一直排队到14点，我的三盒稻香村才装好，一共花了328元
8. 然后拎着三盒非常重的糕点去上班（到现在为止还没吃午饭）
9. 花了308快，为elvestar.com域名续了五年的费用
10. 想搞搞minos的报警，但是没心思，决定不搞，在家每天早晚刷一下minos主页。
11. 18点和韩超出去吃饭，发现沙县关门，于是去十分钟吃，花了24快
12. 19点45分出百度，21点到北京站，21点20分找到位置，躺着开始搞org-mode

* 回家第一天 <2014-01-29 三>

在火车上睡了不到7个小时后醒了，精神很好，喝了两杯水，火车就到沭阳站了。下火车后在
候车大厅处理了一个PCS日志延时的问题，网络比较慢。然后，我离开了沭阳火车站，花五块
钱，坐"马自达"到"大润发"旁边的公交车STOP。等了一会，往龙庙韩山吴集方向的公交车到
了，我上车了，到龙庙的价格还是五块钱。

到了家，爸爸妈妈来迎接我，随行的还有两只狗，其中一只是新狗，才五个月大，品种是北
美。它非常活泼，欢迎我时，使出了乔丹式的后仰跳，还带有一定时长的滞空。

然后，妈妈上街买东西，过了一段时间爸爸说要上街去买春联，于是我们步行上街去了。龙
庙街卖春联的地方很热闹，各家的春联联到了一起，成了一片红色的海洋。我拍了一张很满
意的照片来留念，我觉得这种场景不是每个地方都有的。我们买了10个硬纸做的"福"，花了
15块，然后买了大团透明胶，用来胶春联。

买完春联，我们走回家，路上遇到了我妈。我们三个顺路去五姑工作的地方看看，五姑正好
也在。我们离开时，我妈叮嘱五姑别让我下班后来我们家去拿一个礼物（其实就是我从北京
带来的稻香村）。

下午我再床上休息，五姑打电话过来让我过去"相亲"。我推迟掉了，不想浪费这个时间。

晚上，我研究了下开源的Chromium项目，发现它：
1. 项目真庞大，模块太多了，代码以海量记
2. 它的项目文档看起来很专业，值得我学习
3. 它拥有完善的base库和net库，这真是我梦寐以求的！
   
* 回家第二天，三十年晚 <2014-01-30 四>  

今天早上起床后，在家呆到11点，然后赶去杨湾我舅奶家吃年夜饭。我们三个两辆车，我骑
电瓶车，我爸妈骑摩托。我们顺着那条新建好的公路一路向北，一直开到了大舅家，再也不
用走官墩吴集这条路了，赞，党的政策好！

按照沭阳的风俗，年夜饭是大年三十的中午吃。大舅家的年夜饭很丰盛，我也很爱吃，席间
我们还喝酒了，酒不错，是天之蓝。吃完饭后，我在沙发上玩电脑（想起去年年上我在同一
地点在微博上查许嵩的歌曲）。然后我在大舅家床上睡了一觉，到了四点，我们准备回家。

回家的路上，天气仍然是很阴沉，但不是很冷。到家后，天快晚了，我和爸爸才开始贴春联。
我们先往大门上贴"福"，发现大透明胶不沾！于是爸爸熬了浆（xi）糊（fan），这才把春联
沾上。我疑惑为啥不可以明天在贴呢？可能是按照农历，明天大年初一是春季的第一天，这
时候贴春联就晚了吧。

晚上看了春晚，今年的春晚一如即让地没意思，我基本是在上网和学习的。爸爸看了一会就
说困了，妈妈看得比较晚，妈妈说"好贱"的小品比较好看（我的尾椎啊，都碎了。我还能抢
救得过来吗？）

深夜继续学习，试了几个将HTML转成RST的工具，发现效果都不理想。然后继续学习Ruby on
Rails，尝试了用Rails写了动态网页，CRUD，以及模板填充（erb）。不知不觉过了十二点，
农历新年到了，一大波鞭炮声已经靠近。。。

* 回家第三天，大年初一 <2014-01-31 五>

大年初一，起床吃饭，感觉没啥特别的气氛。不过有个好消息，我弟今天下午到家，我和爸
爸要骑车去沭阳汽车站去迎接。

* 回家第四天 <2014-02-01 六>

* 在家的最后一天 <2014-02-08 六>

昨夜我睡床，我爸睡沙发，妈妈和小晗睡边屋。凌晨三点钟时，OP打电话过来说贴吧的wap日
志延时了。我起床定位了一下，发现他们程序有bug，导致日志量骤增，磁盘频繁被打满。我
爸爸也被吵醒了，意识到我的工作比他想象的要辛苦得多。

早上起床后，洗脸吃饭，妈妈和小晗上街买菜去了，我和爸爸在家里聊天。我向我爸爸介绍
我的新的 *知识管理* 和 *时间管理* 的方式。妈妈回来后，我和爸爸出门去家里租的几亩
花地里面去看看。

吃完午饭，我刚趟床上一会，小芳姐和姐夫就赶过来了。姐夫让我给他下一些歌曲，我看了
下歌曲列表，全部是90年代的青少年们最爱听的歌曲。弄好后，我们准备去沭阳小芳姐家了，
我洗了个头，然后换了衣服，整理下包裹，就往沭阳赶了。

去沭阳的路上发现沭阳的城市风格非常好，比北京的五环外六环内要好很多。到小芳姐家后，
他们开始准备晚饭，我们一家在看电视。房子里没开暖气，有点冷。

从小芳姐家出来，在往火车站的途中想起来忘记带纸杯喝水了，我不好意思回去拿。到了火
车站，和爸爸，妈妈，小晗，大姐，姐夫，子涵告别后，我一个人坐在火车大厅玩电脑，这
时我发现我的背包里面有两个纸杯，这一定是我妈妈在吃晚饭时听我说要带纸杯后怕我忘记
带特意帮我预先装上的，我真的很感动！

9点45分时，我检票进站，在等车时，天气很冷。火车到了，上车时，乘务员说我做错车了，
我的车是晚上12点到！真悲剧啊，我只得返回候车室继续等。

到了候车室，我用3G网卡连上了网，和家里人QQ视频聊天。我想起了刚才做姐夫的车赶往火
车站时车上放的一首歌很好听，这首歌还是我帮他下载的。所以我特意让小晗把今天下午我
为姐夫下载的全部歌曲的列表给截图发过来，从截图中，我认出了这首歌曲的名字叫
*梦的翅膀受了伤* ，歌手是蒋雪儿。
