q地址是：[[http://orgmode.org/manual/index.html][The Org Manual]]。这份文档制作很精良，而且（显然）是用Org-mode写的。
* 学习Org-mode的官方手册

** Wiki式的Inner link
Org-mode支持wiki式的内部链接，格式为：

#+BEGIN_SRC org
[[file:org-mode.org][Org Mode - Organize Your Life In Plain Text!]]
#+END_SRC 

这就让org-mode拥有了写wiki的能力。

** 语言支持
Org-mode支持大量的语言，除了常见的C++，Java，Python外，甚至还支持Graphviz，
Gnuplot，Plantuml等复杂的绘图语言，非常的强大。这是[[http://orgmode.org/manual/Languages.html#Languages][Org-Mode支持的语言列表]]。

* 阅读"Org Mode - Organize Your Life In Plain Text!"
这篇文章据说非常经典，但确实非常长。地址是：[[http://doc.norang.ca/org-mode.html]]

** DONE 前六章读完 <2014-02-06 四>

第六章讲了如何快速地 *Add New Tasks*, 包括下面几个要点：
1. 用Capture Mode来快速Add Task
2. 所有新增的Tasks都加入到一个专门的文件中（refile.org）
4. 为每类Task（如Phone，Meeting，普通Task等）各预设一个模板
5. 快速地完成Task的添加，不中断手头的工作


** Publish and Exporting <2014-02-07 五>
拷贝了作者的emacs lisp脚本，实现了一键批量递归转化为HTML并拷贝到elvestar.com， *
初步将我的新式的知识管理流程给打通了* ，意义很大！
   
** Refile <2014-02-15 六>
看了第七章Refiling Tasks，了解到作者是 *通过refile来将临时放到refile.org中的Task
给移到合适的位置* 。我实践了一下，暂时还摸不清门道，我目前只是拷贝了作者的配置到
自己的.emacs。
*** TODO 有时间，我会深入了解一下refile

* 升级Org-mode版本
我机器上的org-mode版本较低，无法支持批量（Project）地导出为HTML，所以我尝试将其升级为最新的 *Stable version 8.2.5h (Jan. 2014)*

升级步骤：
1. git clone git://orgmode.org/org-mode.git
2. cd org-mode
3. sudo make 
4. sudo make install （注意，默认是安装到/usr/share/emacs/site-lisp/org/）
5. sudo mv \/usr/local/Cellar/emacs/24.3/share/emacs/24.3/lisp/org org_bak （备份老版的org-mode）
6. sudo mv \/usr/share/emacs/site-lisp/org/ \/usr/local/Cellar/emacs/24.3/share/emacs/24.3/lisp/ 

* 在Org中绘图
** 绘制Ascii图
+ [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Picture-Mode.html#Picture-Mode][Emacs Picture Mode]]
+ [[http://www.lysator.liu.se/~tab/artist/][Emacs Artist Mode]]
+ [[http://www.cbi.pku.edu.cn/chinese/documents/csdoc/emacs/chap7.html][图形的编辑（Emacs使用帮助 - pku）]]
+ [[http://lifegoo.pluskid.org/wiki/EmacsEditPicture.html][在 Emacs 里编辑 Ascii 图片]]
+ [[http://emacser.com/artist-mode.htm][用artist-mode画文本图]]
	   
** ditaa	   
文章搜集	   
+ [[http://emacser.com/emacs-ditaa.htm][Emacs中绘图 － ditaa篇]]
+ [[http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-ditaa.html][ob-doc-ditaa - Org-mode]]
		   
有两个关键点：	   
		   
*** 告诉Emacs加载ditaa语言的支持：
#+begin_src emacs-lisp
(org-babel-do-load-languages                                                                        
  (quote org-babel-load-languages)                                                                   
  (quote ((ditaa . t) 
#+end_src	   
 		   
*** 告诉Emacs在哪里找到ditaa的jar文件
#+begin_src emacs-lisp
(setq org-ditaa-jar-path "/usr/local/Cellar/ditaa/0.9/libexec/ditaa0_9.jar") 
#+end_src	   
		   
具体参照	   
		   
* 代码着色（语法高亮）
在我的机器上，/usr/local/Cellar/emacs/24.3/share/emacs/24.3/lisp/org目录下面的
*htmlize.el* 文件负责做代码的着色。如果没找到，则需要下载并拷贝到这下面。

* 将Org文件导出为博客
试了下 [[http://exaos.github.io/o-blog/index.html][o-blog]] ，发现不好用。故决定推迟，先用norang的HTML导出方案。

* 相关文章搜集
+ [[http://www.cnblogs.com/bamanzi/archive/2012/05/12/org-mode-so-powerful.html][为什么说org-mode是个神器]]

* 学习回顾
** 已经入了门 <2014-02-15 六>
经过了春节以及前后的集中学习和实践，我已经将Emacs Org-mode融入到了我的工作和生活
中来了，并且已经初步感受到了它的威力（尤其是在写博客和GTD两方面）。我后续学习的重
点包括：
1. 快速capture task - 有点bug要解决
2. Refile的使用 - 目前还没感受到它的价值
3. Ditta，Graphviz等外围工具的学习
4. 使用一个基于Org-mode的博客生成器，把我的博客重新搭建起来

我的下一步计划是尝试一下基于Org-mode的博客生成器，以及学习如何将已经Done的Task给归档。
