#+TITLE: 阅读 Unix v6 代码
#+DATE: 2014-04-13

* 准备工作
** 书籍
+ John.Lions.Unix.v6.Commentary.Typescript.1977
+ John Lions的书的附带源码

** 源码
我从网上下载了名为unix.v6.v7.src的压缩包，解压后cd到V6/usr/sys下面，然
后使用GNU GLOBAL来生成带交叉引用的HTML源码阅读页面。
#+BEGIN_SRC sh
gtags .
htags -sanohITvFt "UNIX v6 源码" 
#+END_SRC
然后上传到公司的fe.baidu.com上。

* 学习计划
Unix有9099行，但是。。。（见回顾）

* malloc
内存资源分为两种：
+ main memory（单位是64比特）
+ disk swap area（单位是512比特）

两种内存资源都用一个叫做 *map* 的struct来存储：
#+BEGIN_SRC cpp
struct map
{
  char *m_size;
  char *m_addr;
}
#+END_SRC

它们都用systm.h中定义了两个全局变量来保存这两组map：
#+BEGIN_SRC cpp
0203 int  coremap[CMAPSIZ];  /* space for core allocation */
0204 int  swapmap[SMAPSIZ];  /* space for swap allocation */
#+END_SRC

malloc函数的注意点：
1. 依次遍历各个map，选择第一个符合的map（First Fit策略）。
2. 选择好后，如果该map的m_size为0，则将它与下一个map合并（通过遍历该
   map之后的所有map，修改这些map的m_size和m_addr）。
   
* TODO mfree

* printf
函数内部会对格式化串fmt进行遍历：
1. 如果遇到'\0'，则函数退出。
2. 如果遇到整型(%d, %l, %o)，则调用printn打印。
3. 如果遇到字符串(%s)，则调用putchar将字符串挨个字符打印。

该函数原型是：
#+BEGIN_SRC cpp
printf(fmt,x1,x2,x3,x4,x5,x6,x7,x8,x9,xa,xb,xc)
#+END_SRC

函数压栈顺序是从右到左，故fmt在栈顶。由于变量是不固定的，故在遍历格式化
串fmt时，一个变量adx记住函数参数地址，最开始是x1的地址，然后每当在fmt
中遇到一个%，则使adx++，这样adx就指向了下一个参数。在PDP11硬件上，从栈
底到栈顶地址依次下降，故第一次调用adx++，会试adx从指向x1到指向x2，然后
依次类推，直到处理完所有参数。

* printn
被printf调用来打印整型变量，支持十进制和八进制。将数值加上'0'，即可得
到该数值的字符串形式。最终调用的是putchar(c)。

* putchar
要点：
+ 通过写KL(address 0177560)的xbr成员来显示到终端上。
+ 如果KL->xsr&0200等于0，则阻塞住（推测xsr可以用来判断字符是否真正输出
  到终端上）。
+ 如果是putchar('\n')，则会递归调用putchar打印'\r'和两个0177。

* panic
panic函数的实现非常简单：
 #+BEGIN_SRC cpp
2416 panic(s)
2417 char *s;
2418 {
2419    panicstr = s;
2420    update();     // 写完所有的大块buffer
2421    printf("panic: %s\n", s);
2422    for(;;)       // 无限调用idle()
2423        idle();
2424 }
 #+END_SRC

让Unix从panic中恢复的方法只有一个： *重新初始化系统* （伴随着一个
coredump）。

Unix并非一个 "错误容忍" 或 "软性错误" 的系统，当Unix将要进入
*undesirable* 的异常状态钱，它会调用panic函数，然后就进入啥都不做，等
用户来处理的panic状态。Unix的这种设计很符合它的 *保持简单* 的风格。


* 回顾
** 40年的玩意儿真炫酷啊 <2014-04-13 Sun>
真炫酷啊真炫酷。

跟文锋交流，他对OS也很感兴趣，并且深入研究过。

** 中止，转向xv6
当我在准备制定学习计划时，我在网上搜到了xv6：一个根据Unix v6修改出来的，
能运行在x86硬件上，用ANSIC c重写过的，用于教学目的的操作系统。于是，我
动摇了，我准备先补学Unix v6，转而学习 [[./xv6.org][xv6]] 。
