#+TITLE: Zsh (Z shell) - A powerful shell (maybe) better than bash shell
#+OPTIONS: ^:{}

* oh-my-zsh
我是zsh的初学者，为了尽快入手zsh，我选择了使用 [[https://github.com/robbyrussell/oh-my-zsh][oh-my-zsh]] （在MacTalk的 [[http://macshuo.com/?p=676][终极
Shell]]一文的介绍下）。

据作者robbyrussell介绍，oh-my-zsh是一个开源的，社区驱动的，用来管理zsh配置的框架。
它附带了 *数以吨记* 的有价值的函数，插件和主题，以及其它让使用者“大呼过瘾”的有
趣玩意……

* zsh配置相关
** 查看所有选项
直接在zsh中输入 *setopt* 即可查看。在我安装好oh-my-zsh后，setopt的结果如下：

#+BEGIN_SRC sh
➜  ~  setopt             
alwaystoend
autocd
autonamedirs
autopushd
cdablevars
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
#+END_SRC

在上述配置项中： 
- *sharehistory* 代表在多个zsh会话中，共享一份command history。
- *incappendhistory* 代表在command被执行之前就把它保存到history中。

** 禁止多会话间共享command history
多会话间共享command history是oh-my-zsh默认开启的特性，我用起来感觉不适应，因为我
不同的会话是用来干不同的事情的，它们间的comand history不应该混杂到一起，所以我想
关闭它。

该特性相关的配置项是share_history，开启它的指令是setopt share_history。我根据Vim
的使用经验猜测，关闭它的指令是setopt no_share_history。试了一下，发现我猜得没错。

下面是具体的执行步骤；
1. 打开~/.zshrc，加入setopt no_share_history
2. 执行source ~/.zshrc
* zsh的自动补全
zsh的自动补全是最为人陈道的地方。
** kill process-id
** 大小写不感知
** ssh的自动补全hostname
